---
name: ALAN_env
channels:
  - conda-forge
dependencies:
  - python=3.11

  - matplotlib=3.6.3
  - numpy=1.23.5
  - xarray=2022.12.0
  - pyinterp=2023.11.0
  - zarr=2.16.1
  - rasterio=1.3.8
  - netcdf4=1.6.4
  - cartopy=0.22.0
  - shapely=2.0.3
  - pandas=1.5.3
  - geopandas=0.14.3
  - jupyterlab=4.1.1
